// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoodProject.Api;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoodProject.Api.Migrations
{
    [DbContext(typeof(MoodProjectContext))]
    partial class MoodProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MoodProject.Core.Models.ChatRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SymptomId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SymptomId");

                    b.ToTable("ChatRooms");
                });

            modelBuilder.Entity("MoodProject.Core.Models.ChatRoomComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("integer");

                    b.Property<int?>("PostId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("ChatRoomComments");
                });

            modelBuilder.Entity("MoodProject.Core.Models.ChatRoomPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("RoomId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("ChatRoomPosts");
                });

            modelBuilder.Entity("MoodProject.Core.Models.CustomQuizzQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FactorType")
                        .HasColumnType("integer");

                    b.Property<int>("SymptomTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SymptomTypeId");

                    b.ToTable("QuizzQuestions");
                });

            modelBuilder.Entity("MoodProject.Core.Models.FactorValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SymptomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("SymptomId");

                    b.ToTable("FactorValues");
                });

            modelBuilder.Entity("MoodProject.Core.Models.QuizzAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CustomQuizzQuestionId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CustomQuizzQuestionId");

                    b.ToTable("QuizzAnswers");
                });

            modelBuilder.Entity("MoodProject.Core.Models.Symptom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isDisabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Symptoms");
                });

            modelBuilder.Entity("MoodProject.Core.Models.SymptomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SymptomTypes");
                });

            modelBuilder.Entity("MoodProject.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthProviderUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MoodProject.Core.Models.ChatRoom", b =>
                {
                    b.HasOne("MoodProject.Core.Models.Symptom", "Symptom")
                        .WithMany()
                        .HasForeignKey("SymptomId");

                    b.Navigation("Symptom");
                });

            modelBuilder.Entity("MoodProject.Core.Models.ChatRoomComment", b =>
                {
                    b.HasOne("MoodProject.Core.Models.ChatRoomPost", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("MoodProject.Core.Models.ChatRoomPost", b =>
                {
                    b.HasOne("MoodProject.Core.Models.ChatRoom", "Room")
                        .WithMany("Posts")
                        .HasForeignKey("RoomId");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("MoodProject.Core.Models.CustomQuizzQuestion", b =>
                {
                    b.HasOne("MoodProject.Core.Models.SymptomType", "SymptomType")
                        .WithMany()
                        .HasForeignKey("SymptomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SymptomType");
                });

            modelBuilder.Entity("MoodProject.Core.Models.FactorValue", b =>
                {
                    b.HasOne("MoodProject.Core.Models.Symptom", null)
                        .WithMany("ValuesHistory")
                        .HasForeignKey("SymptomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MoodProject.Core.Models.QuizzAnswer", b =>
                {
                    b.HasOne("MoodProject.Core.Models.CustomQuizzQuestion", null)
                        .WithMany("AnswerPossibilities")
                        .HasForeignKey("CustomQuizzQuestionId");
                });

            modelBuilder.Entity("MoodProject.Core.Models.Symptom", b =>
                {
                    b.HasOne("MoodProject.Core.Models.SymptomType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("MoodProject.Core.Models.ChatRoom", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("MoodProject.Core.Models.ChatRoomPost", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("MoodProject.Core.Models.CustomQuizzQuestion", b =>
                {
                    b.Navigation("AnswerPossibilities");
                });

            modelBuilder.Entity("MoodProject.Core.Models.Symptom", b =>
                {
                    b.Navigation("ValuesHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
