
name: .NET Core

on:
  push:
    tags:
      - '**'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: MoodProject    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '7.0.x'           # set this to the dot net version to use

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repo
      - uses: actions/checkout@main
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      # Run dotnet build and publish
      - name: .NET Restore & Build
        run: |
          dotnet restore MoodProject.Api
          dotnet build MoodProject.Api --configuration Release
          dotnet publish  MoodProject.Api -c Release --property:PublishDir='${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/${{ env.AZURE_WEBAPP_NAME }}' 
      
      # Deploy to Azure Web apps
      - name: 'Run Azure webapp deploy action using Azure Credentials'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          package: '/home/runner/work/moodproject/moodproject/MoodProject.Api//${{ env.AZURE_WEBAPP_NAME }}'

      - name: logout
        run: |
          az logout